name: Azure Cleanup Script - Dinesh
on:
  push:
    branches: main
  schedule:
    - cron: '* * * * *'

jobs:
  cron-task:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: test echo
        run: echo "trial run"

      - name: test echo
        run: echo `date`
